#pragma once
#include "mongoose_handler.h"
#include "kinect_grabber.h"
#include "linemod.h"
#include "session_manager.h"
#include "face_detector.h"
#include "sse_handler.h"
#include "hand_detector.h"
#include "opt_parse.h"
#include "key_logger.h"
#include <signal.h>
#include "mongoose.h"
#include "opt.h"
#include "ide_handler.h"